cmake_minimum_required(VERSION 3.16)
project(vku-all)

set(CMAKE_CXX_STANDARD 20)

set(SDL_STATIC TRUE CACHE INTERNAL TRUE)
set(CMAKE_SUPPRESS_REGENERATION true)
set(SDL3_DISABLE_SDL3MAIN ON CACHE BOOL "Disable SDL Entrypoint")
set(SDL3_DISABLE_INSTALL ON CACHE BOOL "Disable SDL Install")
set(SDL3_DISABLE_UNINSTALL ON CACHE BOOL "Disable SDL Uninstall")
set(BUILD_SHARED_LIBS OFF CACHE BOOL "Disable ASSIMP dynamic linking")
set(SHADERC_SKIP_TESTS ON CACHE BOOL "" FORCE)
set(SHADERC_ENABLE_SHARED_CRT ON CACHE BOOL "" FORCE)

add_subdirectory(submodules/glm)
add_subdirectory(submodules/assimp)
add_subdirectory(submodules/sdl)
add_subdirectory(submodules/volk)
add_subdirectory(submodules/SPIRV-headers)
add_subdirectory(submodules/SPIRV-tools)
add_subdirectory(submodules/glslang)
add_subdirectory(submodules/shaderc)

set(ASSIMP_INCLUDES		${CMAKE_CURRENT_SOURCE_DIR}/submodules/assimp/include CACHE INTERNAL "")
set(GLM_INCLUDES		${CMAKE_CURRENT_SOURCE_DIR}/submodules/glm CACHE INTERNAL "")
set(SPDLOG_INCLUDES		${CMAKE_CURRENT_SOURCE_DIR}/submodules/spdlog/include CACHE INTERNAL "")
set(SDL_INCLUDES		${CMAKE_CURRENT_SOURCE_DIR}/third-party/sdl/include CACHE INTERNAL "")
set(SHADERC_INCLUDES	${CMAKE_CURRENT_SOURCE_DIR}/submodules/shaderc/libshaderc/include CACHE INTERNAL "")
set(CPPTRACE_INCLUDES	${CMAKE_CURRENT_SOURCE_DIR}/submodules/cpptrace/include CACHE INTERNAL "")

set(SHADERC_UTIL_INCLUDES ${CMAKE_CURRENT_SOURCE_DIR}/submodules/shaderc/libshaderc_util/include CACHE INTERNAL "")

set_target_properties(glm PROPERTIES			FOLDER "ThirdParty/glm")
set_target_properties(SDL3_test PROPERTIES		FOLDER "ThirdParty/SDL")
set_target_properties(SDL3-static PROPERTIES	FOLDER "ThirdParty/SDL")

add_subdirectory(vku)
add_subdirectory(backends/sdl)
add_subdirectory(examples/msaa)
add_subdirectory(examples/nanovg)
add_subdirectory(examples/lights-forward)
add_subdirectory(examples/im3d-multiview)
add_subdirectory(examples/compute)
add_subdirectory(examples/dynamic-rendering)
